### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by souporserious** [planningcenter/twain#6]
Not to be overly dramatic, but per the current social climate around sexual harassment, naming the library `Consent` doesn't feel the most appropriate. There are other names that aren't triggering and fit Planning Center's culture more. I'd personally love to come to an agreement on a library name as a team.

**Comment by chantastic** [comment]
the name perfectly encapsulates the goal of the project, which is consensus.

> permission for something to happen or agreement to do something.

it can easily be changed once the primary goals are met. i'll ask the rest of those on the team if they have any concern with the name as it is

**Comment by chantastic** [comment]
do you plan on using thisnin Services?

**Comment by joshwilkerson** [comment]
I think I agree with Travis... the word `consent`, at face value, can have a complicated connotation. What if we use `consensus`? To me, that conveys a feeling of "multiple parties agreeing" to something vs. "2 parties" that is generally implied by `consent`

**Comment by chantastic** [comment]
had a clarifying conversation with @tage about the role of these experimentations to the design spec. and while this experimentation is important in clarifying parts of the spec, trying to gain "consensus" on this and the spec simultaneously is an overwhelming amount of discussion for the team.

in light of that, I've changed tho code name to `twain` — a joke at the difficulty in mapping React and CSS in cogent way.

I trust that `twain` is less objectionable.
